import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProvider";
import Header from "./components/header/Header";
import "../lib/i18n";
import ScrollToTop from "./components/ScrollToTop";
import { CartProvider } from "./context/CartContext";
import { ToastContainer } from "react-toastify"; import "react-toastify/dist/ReactToastify.css";
import ChatWidget from "./components/chat/ChatWidget";
import Footer from "./components/Futer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ScrollToTop />
        <CartProvider>
          <ThemeProvider>
            <Header />
            <main className="mt-12 md:mt-25 sm:mt-20">
              {children}
              
            </main>
            <ToastContainer 
            />
          </ThemeProvider>
        </CartProvider>
        <Footer/>
        <ChatWidget />
      </body>
    </html>
  );
}
